/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BN5aSZU42Or
 */
import { Button } from "@/components/button"

export function MainScreen() {
  return (
    <main
      key="1"
      className="w-full h-screen grid grid-cols-1 md:grid-cols-3 gap-4 p-4 bg-gray-100 dark:bg-gray-900 relative"
    >
      <header className="col-span-full mb-4">
        <h1 className="text-3xl font-bold text-center text-blue-600 dark:text-blue-300">
          Hackathon 2024 Vegas - Team XYZ
        </h1>
      </header>
      <section className="flex flex-col bg-white dark:bg-gray-800 p-4 rounded-md shadow-md h-full min-h-screen">
        <h2 className="text-xl font-semibold mb-2 flex justify-between items-center">
          Conversation 1
          <span className="px-2 py-1 text-sm font-semibold rounded-md bg-red-500 text-white">Very Negative</span>
          <span className="px-2 py-1 text-sm font-semibold rounded-md bg-yellow-500 text-white" id="982bcyttttp">
            Neutral
          </span>
          <span className="px-2 py-1 text-sm font-semibold rounded-md bg-green-500 text-white" id="982bcyttttp">
            Positive
          </span>
        </h2>
        <div
          className="flex-1 overflow-auto bg-gray-100 dark:bg-gray-700 p-2 rounded-md"
          
        >
          <p className="text-gray-500 dark:text-gray-400">Customer: Hello, I need help with my account.</p>
          <p className="text-gray-500 dark:text-gray-400">
            Bot: Sure, I'd be happy to assist you. What seems to be the problem?
          </p>
          <p className="text-gray-500 dark:text-gray-400">Customer: I can't log in to my account.</p>
          <p className="text-gray-500 dark:text-gray-400">Bot: I see. Let's try resetting your password.</p>
          <p className="text-gray-500 dark:text-gray-400">Customer: Okay, let's do that.</p>
          <p className="text-gray-500 dark:text-gray-400">Bot: I've sent a password reset link to your email.</p>
        </div>
        <div className="flex gap-2 mt-4">
          <Button>Give instructions</Button>
          <Button>Hijack call</Button>
        </div>
      </section>
      <section className="flex flex-col bg-white dark:bg-gray-800 p-4 rounded-md shadow-md h-full">
        <h2 className="text-xl font-semibold mb-2">Conversation 2</h2>
        <div className="flex-1 overflow-auto bg-gray-100 dark:bg-gray-700 p-2 rounded-md">
          <p className="text-gray-500 dark:text-gray-400">Customer: Hi, I'm having trouble with my payment.</p>
          <p className="text-gray-500 dark:text-gray-400">
            Bot: I'm sorry to hear that. Could you please tell me more about the issue?
          </p>
          <p className="text-gray-500 dark:text-gray-400">Customer: My payment isn't going through.</p>
          <p className="text-gray-500 dark:text-gray-400">Bot: Let's check your payment details.</p>
          <p className="text-gray-500 dark:text-gray-400">Customer: Okay, thanks.</p>
          <p className="text-gray-500 dark:text-gray-400">Bot: I've updated your payment details. Please try again.</p>
        </div>
        <div className="flex gap-2 mt-4">
          <Button>Give instructions</Button>
          <Button>Hijack call</Button>
        </div>
      </section>
      <section className="flex flex-col bg-yellow-200 dark:bg-yellow-700 p-4 rounded-md shadow-md h-full">
        <h2 className="text-xl font-semibold mb-2">Conversation 3</h2>
        <div className="flex-1 overflow-auto bg-gray-100 dark:bg-gray-700 p-2 rounded-md">
          <p className="text-gray-500 dark:text-gray-400">Customer: Hello, I can't access my dashboard.</p>
          <p className="text-gray-500 dark:text-gray-400">
            Bot: I'm sorry for the inconvenience. Let's try to resolve this.
          </p>
          <p className="text-gray-500 dark:text-gray-400">Customer: Great, thank you.</p>
          <p className="text-gray-500 dark:text-gray-400">
            Bot: I've refreshed your dashboard access. Please try logging in again.
          </p>
          <p className="text-gray-500 dark:text-gray-400">Customer: It worked! Thank you.</p>
          <p className="text-gray-500 dark:text-gray-400">
            Bot: You're welcome! If you have any other issues, feel free to ask.
          </p>
        </div>
        <div className="flex gap-2 mt-4">
          <Button>Give instructions</Button>
          <Button>Hijack call</Button>
        </div>
      </section>
      <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-blue-200 dark:bg-blue-700 p-4 rounded-md shadow-md w-128 h-80">
        <header className="flex justify-between items-center mb-4">
          <h3 className="text-lg font-semibold">Conversation 1</h3>
          <h3 className="text-lg font-semibold">Add Instructions</h3>
        </header>
        <div className="flex-1 overflow-auto bg-gray-100 dark:bg-gray-700 p-2 rounded-md mb-4">
          <textarea className="w-full h-full resize-none bg-transparent" placeholder="Type your instructions here..." />
        </div>
        <Button>Send Message</Button>
      </div>
    </main>
  )
}
